/** Shared diagnostic contract; renderer translates keys, never raw CLI diagnostics. */
export const ANTIGRAVITY_ERROR_KEYS = {
  ANTIGRAVITY_ARTIFACT_UNSAFE: "antigravity.errors.unsafeArtifact",
  ANTIGRAVITY_ARTIFACT_UNVERIFIED: "antigravity.errors.unsafeArtifact",
  ANTIGRAVITY_CANCELLED: "antigravity.errors.cancelled",
  ANTIGRAVITY_CLEANUP_FAILED: "antigravity.errors.cleanupFailed",
  ANTIGRAVITY_CLEANUP_TIMEOUT: "antigravity.errors.cleanupFailed",
  ANTIGRAVITY_CONVERSATION_MISMATCH: "antigravity.errors.protocolMismatch",
  ANTIGRAVITY_DRAIN_TIMEOUT: "antigravity.errors.drainTimeout",
  ANTIGRAVITY_DUPLICATE_RESULT: "antigravity.errors.protocolMismatch",
  ANTIGRAVITY_EMPTY_PROMPT: "antigravity.errors.emptyPrompt",
  ANTIGRAVITY_EMPTY_RESPONSE: "antigravity.errors.emptyResponse",
  ANTIGRAVITY_EXECUTABLE_CHANGED: "antigravity.errors.executableChanged",
  ANTIGRAVITY_EXECUTABLE_INVALID: "antigravity.errors.executableInvalid",
  ANTIGRAVITY_EXECUTABLE_UNPREPARED: "antigravity.errors.preflightRequired",
  ANTIGRAVITY_HANDSHAKE_MISMATCH: "antigravity.errors.handshakeMismatch",
  ANTIGRAVITY_HOOK_PATH_INVALID: "antigravity.errors.hookPathInvalid",
  ANTIGRAVITY_HOOK_UNVERIFIED: "antigravity.errors.hookUnverified",
  ANTIGRAVITY_IMAGE_INVALID: "antigravity.errors.invalidImage",
  ANTIGRAVITY_IMAGE_SOURCE_INVALID: "antigravity.errors.invalidImage",
  ANTIGRAVITY_INIT_REQUIRED: "antigravity.errors.profileUnverified",
  ANTIGRAVITY_INIT_TIMEOUT: "antigravity.errors.initTimeout",
  ANTIGRAVITY_INVALID_CAPABILITY: "antigravity.errors.invalidRequest",
  ANTIGRAVITY_INVALID_IMAGES: "antigravity.errors.invalidImage",
  ANTIGRAVITY_INVALID_INIT: "antigravity.errors.profileUnverified",
  ANTIGRAVITY_INVALID_JSON: "antigravity.errors.protocolMismatch",
  ANTIGRAVITY_INVALID_MODEL: "antigravity.errors.modelUnavailable",
  ANTIGRAVITY_INVALID_PROTOCOL: "antigravity.errors.protocolMismatch",
  ANTIGRAVITY_INVALID_RESULT: "antigravity.errors.protocolMismatch",
  ANTIGRAVITY_INVALID_STEP: "antigravity.errors.protocolMismatch",
  ANTIGRAVITY_INVALID_TEST: "antigravity.errors.invalidRequest",
  ANTIGRAVITY_INVALID_USAGE: "antigravity.errors.protocolMismatch",
  ANTIGRAVITY_LOGIN_REQUIRED: "antigravity.errors.loginRequired",
  ANTIGRAVITY_MEDIA_INCOMPLETE: "antigravity.errors.incompleteMedia",
  ANTIGRAVITY_MISSING_RESULT: "antigravity.errors.emptyResponse",
  ANTIGRAVITY_MODELS_INVALID: "antigravity.errors.probeFailed",
  ANTIGRAVITY_MODEL_NOT_DISCOVERED: "antigravity.errors.modelUnavailable",
  ANTIGRAVITY_MODEL_UNAVAILABLE: "antigravity.errors.modelUnavailable",
  ANTIGRAVITY_NOT_INSTALLED: "antigravity.errors.notInstalled",
  ANTIGRAVITY_OUTPUT_LIMIT: "antigravity.errors.outputLimit",
  ANTIGRAVITY_OWNER_MISMATCH: "antigravity.errors.ownerMismatch",
  ANTIGRAVITY_PREFLIGHT_MISMATCH: "antigravity.errors.preflightRequired",
  ANTIGRAVITY_PREPARED_MEDIA_INVALID: "antigravity.errors.preflightRequired",
  ANTIGRAVITY_PREPARED_TASK_INVALID: "antigravity.errors.preflightRequired",
  ANTIGRAVITY_PROBE_FAILED: "antigravity.errors.probeFailed",
  ANTIGRAVITY_PROCESS_FAILED: "antigravity.errors.processFailed",
  ANTIGRAVITY_PROFILE_UNVERIFIED: "antigravity.errors.profileUnverified",
  ANTIGRAVITY_QUOTA: "antigravity.errors.quota",
  ANTIGRAVITY_RESPONSE_MISMATCH: "antigravity.errors.protocolMismatch",
  ANTIGRAVITY_SHUTTING_DOWN: "antigravity.errors.shuttingDown",
  ANTIGRAVITY_TEST_ACTIVE: "antigravity.errors.busy",
  ANTIGRAVITY_TEST_ARTIFACT_MISSING: "antigravity.errors.incompleteMedia",
  ANTIGRAVITY_TEST_ASSERTION_FAILED: "antigravity.errors.testFailed",
  ANTIGRAVITY_TEST_FAILED: "antigravity.errors.testFailed",
  ANTIGRAVITY_TEST_REQUIRED: "antigravity.errors.testRequired",
  ANTIGRAVITY_TIMEOUT: "antigravity.errors.timeout",
  ANTIGRAVITY_TOOLS_UNSUPPORTED: "antigravity.errors.toolDenied",
  ANTIGRAVITY_TOOL_BUDGET: "antigravity.errors.toolDenied",
  ANTIGRAVITY_TOOL_FAILED: "antigravity.errors.toolFailed",
  ANTIGRAVITY_UNSUCCESSFUL_RESULT: "antigravity.errors.processFailed",
  ANTIGRAVITY_UNSUPPORTED_EVENT: "antigravity.errors.protocolMismatch",
  ANTIGRAVITY_VERSION_TOO_OLD: "antigravity.errors.versionTooOld",
  ANTIGRAVITY_VERSION_UNRECOGNIZED: "antigravity.errors.versionUnknown",
  ANTIGRAVITY_WINDOWS_UNSUPPORTED: "antigravity.errors.windowsUnsupported",
} as const;

export function antigravityErrorKey(code: string): typeof ANTIGRAVITY_ERROR_KEYS[keyof typeof ANTIGRAVITY_ERROR_KEYS] {
  return Object.prototype.hasOwnProperty.call(ANTIGRAVITY_ERROR_KEYS, code)
    ? ANTIGRAVITY_ERROR_KEYS[code as keyof typeof ANTIGRAVITY_ERROR_KEYS]
    : ANTIGRAVITY_ERROR_KEYS.ANTIGRAVITY_TEST_FAILED;
}
